'use strict';mix_d("AmazonHomepageSolitaireCards__single-asin-multi-image:single-asin-multi-image__mLD3GTJr","exports tslib @c/dom @p/A @p/a-carousel-framework @p/a-truncate @c/aui-utils".split(" "),function(q,r,t,C,D,E,u){function h(a){return a&&"object"===typeof a&&"default"in a?a:{"default":a}}var k=h(t),l=h(C),m=h(D),F=h(E),G=function(a){return 9<a?String(a):"0".concat(a)},n=function(a){if(0>=a)return"00:00";var b=Math.floor(a/36E5);a=[Math.floor(a/6E4%60),Math.floor(a/1E3%60)];0<b&&a.unshift(b);
return a.map(G).join(":")},J=function(a,b){var c=Array.prototype.slice.call(a.querySelectorAll("[data-component='badge-countdown-timer']")).map(function(d){if(!d.dataset.targetTime&&!d.dataset.absoluteTargetTime)return function(){};H(d);return I(d,b)});return function(){return c.forEach(function(d){return d()})}},K=function(a){Array.prototype.slice.call(a.querySelectorAll("[data-component='dui-badge']")).forEach(function(b){b&&32<b.offsetHeight&&(null===b||void 0===b?void 0:b.setAttribute("data-align",
"vertical"))})},I=function(a,b){if("true"===a.dataset.initialized||!a.dataset.absoluteTargetTime)return function(){};a.dataset.initialized="true";var c=Number(a.dataset.absoluteTargetTime),d=c-Date.now();0<d&&(a.innerText=n(d));var f=b(function(){var e=c-Date.now();0>=e?(a.innerText=n(0),clearInterval(f)):a.innerText=n(e)},500);return function(){a.dataset.initialized="false";clearInterval(f)}},H=function(a){if(!a.dataset.absoluteTargetTime){var b=Number(a.dataset.targetTime),c=Date.now();b=Number.isNaN(b)?
c:b+c;a.dataset.absoluteTargetTime=String(b)}},L=function(a){Array.prototype.slice.call(a.getElementsByClassName("a-truncate")).forEach(function(b){return F["default"].get(t.unscope(b)).update()})},v=!1,g,N=function(a){var b=a.getElementsByClassName("_single-asin-multi-image_style_productBlock__3kpEI")[0],c=a.getElementsByClassName("a-carousel-container")[0];if(b&&c){var d=b.dataset.name;m["default"].onInit(d,function(){m["default"].getCarouselByName(d).gotoPage(1);g=c.dataset.aClass;M(d,a);if("mobile"===
g){L(a);var f=Array.prototype.slice.call(a.getElementsByClassName("a-pagination"));if(f)l["default"].on("a:carousel:"+d+":change:pageNumber",function(e){var w=Array.prototype.slice.call(f[1].children);w[e.oldValue-1].classList.remove("a-selected");w[e.newValue-1].classList.add("a-selected")})}})}},M=function(a,b){O(a,b);l["default"].on("a:carousel:"+a+":change:pageNumber",function(c){P(a,b);p(b.getElementsByClassName("image-"+(c.oldValue-1))[0]);x(b.getElementsByClassName("image-"+(c.newValue-1))[0])})},
O=function(a,b){x(b.getElementsByClassName("image-0")[0]);Array.prototype.slice.call(b.getElementsByClassName("_single-asin-multi-image_style_eagerlyLazyLoadedCarouselElement__1-osN")).forEach(function(c){y(c);p(c);z(c,a)})},P=function(a,b){v||(Array.prototype.slice.call(b.getElementsByClassName("_single-asin-multi-image_style_lazyLoadedCarouselElement__3xqhH")).forEach(function(c){y(c);p(c);z(c,a)}),v=!0)},y=function(a){var b=a.getElementsByClassName("_single-asin-multi-image_style_lazyLoadedImage__14WQq")[0];
b&&(l["default"].loadImageManually(b),a.getElementsByClassName("_single-asin-multi-image_style_lazyLoadedImage__14WQq")[0].complete?A(a):a.getElementsByClassName("_single-asin-multi-image_style_lazyLoadedImage__14WQq")[0].addEventListener("load",function(){A(a)}))},z=function(a,b){if("mobile"===g){var c=a.getElementsByClassName("_single-asin-multi-image_style_productImage__37qzN")[0];c&&a.addEventListener("click",function(){m["default"].getCarouselByName(b).gotoPage(parseInt(c.id))})}},A=function(a){var b=
a.getElementsByClassName("_single-asin-multi-image_style_imageLoadingSpinner__1BUWP")[0];b&&b.remove();a.classList.remove("_single-asin-multi-image_style_lazyLoadedCarouselElement__3xqhH")},p=function(a){a.style.opacity=.3;"mobile"===g&&(a.children[0].style.pointerEvents="none",a.children[0].setAttribute("aria-disabled","true"))},x=function(a){a.style.opacity=1;"mobile"===g&&(a.children[0].style.pointerEvents="auto",a.children[0].setAttribute("aria-disabled","false"))},Q=function(a){return 9<a?String(a):
"0"+a},B=function(a){if(0>=a)return"00:00";var b=Math.floor(a/36E5);a=[Math.floor(a/6E4%60),Math.floor(a/1E3%60)];0<b&&a.unshift(b);return a.map(Q).join(":")},S=function(a){Array.prototype.slice.call(a.getElementsByClassName("badge-countdown-timer")).forEach(function(b){(new R(b)).start()})},R=function(){function a(b){this.timerElement=b;this.msToEvent=parseInt(b.dataset.time,10);this.timerElement.innerText=B(this.msToEvent)}a.prototype.start=function(){var b=this;isNaN(this.msToEvent)||(this.counterStartTime=
Date.now(),this.counterInterval=u.interval(function(){return b.updateTime()},500))};a.prototype.updateTime=function(){var b=Date.now()-this.counterStartTime;0>=this.msToEvent-b&&clearInterval(this.counterInterval);this.timerElement.innerText=B(this.msToEvent-b)};return a}();q._operationNames=[];q.card=function(){return r.__awaiter(void 0,void 0,void 0,function(){return r.__generator(this,function(a){N(k["default"].cardRoot);S(k["default"].cardRoot);a=k["default"].cardRoot;J(a,u.interval);K(a);return[2]})})}});
